### ISSUE TITLE
Segundo feedback portafolio

### ISSUE THREAD

**Issue by adolivaresl** [KarenQuezadaMejia/karenQuezada.github.io#1]
Hola Karen, revisé tu portafolio este es el feedback: cambió 100% desde la primera revisión, me gusta tu paleta de colores y el efecto parallax. En la versión para desktop ojo con la tipografía para textos largos cuesta su lectura ya que la tipo de por sí es muy fina y el espaciado y bastante poco, también pondría el tamaño más grande, en el caso de la versión mobile se lee bastante bien. Falta corregir el tema de los márgenes, la sección "Sobre mí" el texto y el título está muy pegado al borde. En la sección de "herramientas" ojo con los logos si estos van a ser vectorizados y calados entonces todos deben seguir la misma línea y busca una forma que la alineación se vea equilibrada (no debería quedar uno solo si los demás están alineados de pares). Los botones "sobre mi" y "mis proyectos" no funcionan y falta que coloques los de "mis habilidades" y "contacto", también que coloques las fotografías que utilizarás.

**Comment by KarenQuezadaMejia** [comment]
Hola America, hice la corrección que me indicaste, modifique la tipografía, le di espacios al texto,y enlace los botones,  aún no tengo definidas las imágenes que incluiré en el portafolio y continúo trabajando para poder editar los iconos de las herramientas en un mismo tamaño.

**Comment by KarenQuezadaMejia** [comment]
Hola America, hice la corrección que me indicaste, modifique la tipografía, le di espacios al texto,y enlace los botones, aún no tengo definidas las imágenes que incluiré en el portafolio y continúo trabajando para poder editar los iconos de las herramientas en un mismo tamaño.
